apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplejob-manager
  namespace: system
  labels:
    control-plane: samplejob-manager
spec:
  selector:
    matchLabels:
      control-plane: samplejob-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: samplejob-manager
    spec:
      securityContext:
        runAsUser: 65532
      containers:
        - command:
            - /manager
          args:
            - --leader-elect
            - --namespace=paddle-system
          image: samplejob:latest
          imagePullPolicy: Always
          name: manager
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 20Mi
      terminationGracePeriodSeconds: 10