# permissions for end users to edit samplesets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sampleset-editor-role
rules:
- apiGroups:
  - batch.paddlepaddle.org
  resources:
  - samplesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.paddlepaddle.org
  resources:
  - samplesets/status
  verbs:
  - get
