apiVersion: batch.paddlepaddle.org/v1
kind: PaddleJob
metadata:
  name: deepfm
spec:
  cleanPodPolicy: OnFailed
  withGloo: 1
  tasks:
  - name: ps
    replicas: 2
    template:
      spec:
        containers:
          - name: paddle
            image: registry.baidubce.com/paddle-operator/demo-deepfm:v1
            imagePullPolicy: Always
            command:
            - python3
            args:
            - train.py
  - name: worker
    replicas: 2
    template:
      spec:
        containers:
          - name: paddle
            image: registry.baidubce.com/paddle-operator/demo-deepfm:v1
            imagePullPolicy: Always
            command:
            - python3
            args:
            - train.py
