apiVersion: batch.paddlepaddle.org/v1alpha1
kind: SampleSet
metadata:
  name: imagenet
spec:
  partitions: 2
  sources:
    - uri: https://imagenet.bj.bcebos.com/juicefs
      name: imagenet
#  csi:
#    driver: juicefs
#  cache:
#    levels:
#      - mediumType: MEM
#        path: /dev/shm/imagenet
#        quota: 100Mi
#      - mediumType: HDD
#        path: /data/imagenet
#        quota: 100Gi
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: sampleset
              operator: In
              values:
                - "imagenet"