apiVersion: batch.paddlepaddle.org/v1alpha1
kind: SampleSet
metadata:
  name: imagenet
spec:
  partitions: 2
  sources:
    - uri: https://imagenet.bj.bcebos.com/juicefs
      name: imagenet
  secretRef:
    name: imagenet
#  csi:
#    driver: juicefs
#    juiceFSMountOptions:
#  cache:
#    levels:
#      - mediumType: MEM
#        path: /dev/shm/imagenet
#        cacheSize: 1024
#      - mediumType: HDD
#        path: /data/imagenet
#        cacheSize: 1024
#  nodeAffinity:
#    required:
#      nodeSelectorTerms:
#        - matchExpressions:
#            - key: sampleset
#              operator: In
#              values:
#                - "imagenet"