apiVersion: batch.paddlepaddle.org/v1alpha1
kind: SampleSet
metadata:
  name: imagenet
spec:
  partitions: 2
  source:
    uri: https://imagenet.bj.bcebos.com/juicefs
  secretRef:
    name: imagenet
  csi:
    driver: juicefs
    juiceFSMountOptions:
      cache-size: 10240
      open-cache: 2048
  cache:
    levels:
      - mediumType: MEM
        path: /dev/shm/imagenet-0:/dev/shm/imagenet-1
        cacheSize: 1024
#      - mediumType: HDD
#        path: /data/imagenet
#        cacheSize: 1024
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: sampleset
              operator: In
              values:
                - "imagenet"