apiVersion: apps/v1
kind: Deployment
metadata:
  name: paddle-operator
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: paddle-operator
  template:
    metadata:
      labels:
        app: paddle-operator
    spec:
      volumes:
      - name: kube-config-volume
        hostPath:
          # directory location on host
          path: {{ .Values.kubeconfig.location }}/.kube
          type: Directory
      containers:
      - name: {{ .Chart.Name }}
        volumeMounts:
        - mountPath: /.kube
          name: kube-config-volume
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}/paddle-operator:{{ .Values.image.tag }}"
        args: ["-kubeconfig", "/.kube/config", "-autoclean"]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
